# Use root/example as user/password credentials
version: '3.1'

services:

  configServer:
    image: configserver-image
    build: configserver/
    restart: always
    container_name: config-server
    depends_on:
      - eureka
    ports:
      - 8888:8888

  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    container_name: mysqlserver
    network_mode: host
    hostname: localhost
    volumes:
      - $HOME/mysql:/var/lib/mysql
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: users
      MYSQL_PASSWORD: Root@123

  eureka:
      image: eureka-image
      build: eurekaserver/
      restart: always
      container_name: eureka
      ports:
        - 8761:8761

  mongo:
    image: mongo-image
    container_name: mongo
    restart: always
    volumes:
      - $HOME/mongo:/data/db/

  apiGateway: 
    image: api-interfaceimage
    build: apiinterface/
    restart: always
    container_name: api-interface
    depends_on:
      - users
      - movie
      - eureka
    ports: 
          - 8777:8777


  movie: 
    image: movie-image
    build: Movie-RestFul-API-using-Spring-Boot-MongoDatabase/
    restart: always
    container_name: movie-service
    depends_on:
      - mongo
      - eureka
      - configServer
    ports:
      - 8083:8083

  users:
    image: user-image
    build: UserService/
    restart: always
    container_name: users
    ports:
          - 8082:8083
    depends_on:
      - eureka
      - configServer
      - mysql
